modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (26 is current forge version)
[[mods]] #mandatory
modId="tobrirsgarden" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Tobrirs Garden" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
It just gardening
'''